version: '3'

services:
  neo4j:
    image: neo4j:latest
    network_mode: "bridge"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4j_dbms_memory_pagecache_size=1G
      - NEO4j_dbms.server.memory.heap.initial_size=1G
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      
    volumes:
      - ./plugins:/plugins
      - ./data:/data - ./import:/import