apiVersion: v1
kind: Service
metadata:
  labels:
    app: jeus-echo
  name: jeus-echo-svc
  spec:
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: jeus-echo
    type: LoadBalancer