apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jeus-todo
  name: jeus-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jeus-todo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jeus-todo
      annotations:
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - image: 192.168.2.10:8443/jeus-todo
        name: jeus-echo
        resources: {}
status: {}