apiVersion: v1
kind: PersistentVolume
metadata:
  name: jeus-blog-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.2.10
    path: /nfs_shared/blog
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jeus-blog-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi