apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeus-nginx-deployment
  labels:
    app: jeus-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jeus-nginx
  template:
    metadata:
      labels:
        app: jeus-nginx
    spec:
      containers:
      - name: jeus-nginx
        image: jeus-nginx:0.0.1
        ports:
        - containerPort: 80