version: '3'
services:
  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - 8001:8001
    volumes:
      - ./data/redisinsight:/db
    depends_on:
      - redis