apiVersion: v1
kind: Service
metadata:
  labels:
    app: jeus-blog
  name: jeus-blog-svc
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: jeus-blog
  type: LoadBalancer